sequenceDiagram
  participant Browser as Browser
  participant Server as Server

  Browser ->> Server: GET https://studies.cs.helsinki.fi/exampleapp/spa
  Server ->> Browser: HTML document
  Browser ->> Server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
  Server ->> Browser: CSS file
  Browser ->> Server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
  Server ->> Browser: JScript file
  Note right of Browser: Browser executes code to fetch JSON from server
  Browser ->> Server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
  Server ->> Browser: JSON file
  Note right of Browser: Browser executes call back function to render Notes List

